### ISSUE TITLE
mixin gridle_parent() not working as expected

### ISSUE THREAD

**Issue by MichalZalecki** [olivierbossel/gridle#14]
I found a bug (or a feature not mentioned in the docs :smile:). I'm starting project and I pic Gridle over inuit.css grid. gridle_parent mixin not working properly when state isn't specified. It's easy to fix by passing "default" as a state. Maby I'm just doing something wrong.

_grid-settings.scss:

``` scss
// Import gridle :
@import 'gridle/gridle';

// setup the grid (required) :
@include gridle_setup((
    context : 12,
    gutter-width : 24px,
    debug : false
));

@include gridle_register_default_mobile_first_states();
```

grid.scss:

``` scss
// Import grid settings :
@import 'grid-settings';

.wrapper {
    @include gridle_container();
    max-width: 1000px;
    margin: 0 auto
}

.content,
.footer,
.sidebar--footer {
    @include gridle(12);
    @include gridle_parent("default");
}

.main {
    @include gridle(6);
}

.sidebar,
.widget {
    @include gridle(3);
}

.widget {
    background: #bada55;
}

.sidebar {
    background: #c0ff33;
}
```

index.html:

``` html
<div class="wrapper gridle-debug">
    <div class="content">
        <div class="sidebar">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam facere esse quod harum. Quae, recusandae, quaerat odit optio ab eius magni fugiat quis repudiandae rerum quos soluta ut blanditiis ad.</div>
        <main class="main">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Suscipit voluptatum optio mollitia minus beatae. Rerum, placeat, deserunt, atque saepe nesciunt modi repudiandae eaque qui amet officia quisquam reiciendis quibusdam dolor!</main>
        <div class="sidebar">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quam facere esse quod harum. Quae, recusandae, quaerat odit optio ab eius magni fugiat quis repudiandae rerum quos soluta ut blanditiis ad.</div>
    </div>
    <div class="footer">
        <div class="sidebar--footer">
            <div class="widget">Lorem ipsum...</div>
            <div class="widget">Lorem ipsum...</div>
            <div class="widget">Lorem ipsum...</div>
            <div class="widget">Lorem ipsum...</div>
        </div>
    </div>
</div>
```

![screenshot_00095](https://cloud.githubusercontent.com/assets/3136577/3121318/f1d4f6de-e75a-11e3-9fbb-cc644c307ff2.png)

When I change

``` scss
gridle_parent("default")
```

to:

``` scss
gridle_parent()
```

It looks pretty lame

![screenshot_00096](https://cloud.githubusercontent.com/assets/3136577/3121391/c029760e-e75b-11e3-9e88-4bfb7abc0a31.png)

it's because of overwriting padding-left: 0; and padding-right: 0; by default state media query. 

Gridle.scss is awesome and I hope it'll by fixed soon...
