### ISSUE TITLE
Clean way to write multiple @include gridle_...

### ISSUE THREAD

**Issue by olivierbossel** [olivierbossel/gridle#18]
Reported "issue" :

Is there a more efficient way of doing this? @include gridle( 12, tablet-portrait ); @include gridle_push( 0, tablet-portrait ); @include gridle( 12, tablet-portrait ); @include gridle_push( 0, tablet-portrait ); @include gridle( 12, mobile ); @include gridle_push( 0, mobile );

Solution :

There's now the @include gridle_state that let you write cleaner sass like so :

``` scss
#myCoolSidebar {

    /**
     * Default usage :
     */
    // set the default values
    @include gridle_set( (
        grid : 4,
        push : 8
    ) );

    // erase values for tablet
    @include gridle_set( (
        grid : 12,
        push : 0
    ), tablet );
    // you can also pass ( tablet, mobile ) as {state} param to apply to multiple states at once

    // hide on mobile :
    @include gridle_hide( mobile );

    /**
     * ------------------ OR --------------------
     */

    /**
     * Or pass your states directly in one gridle_set call :
     * !!! do not set any state as second parameter with this solution
     * Be careful to not have any states that match a reserved gridle setting name like push, pull, etc...
     */
    @include gridle_set( (
        grid : 4,
        push : 8,
        tablet : (
            grid : 12,
            push : 0
        )
    ) );
}
```

cf. Documentation for more informations :
http://gridle.org/documentation

Cheers !
