### ISSUE TITLE
Redundant(?) media queries, can't find how to clean it up.

### ISSUE THREAD

**Issue by MichalZalecki** [olivierbossel/gridle#20]
Hi! 

I found out that when I'm using mixins for creating grid I get a lot of redundant queries. E.g.:

```SCSS
.primary {
	@include gridle_set( (
        grid : 24
	) );
}
```

Gives me that:

```SCSS
@media screen and (max-width: 99999999px) {
  /* line 29, layout\_grid.scss */
  .primary {
    float: left;
    direction: ltr;
    padding-left: 12px;
    padding-right: 12px;
  }
}
@media screen and (max-width: 480px) {
  /* line 29, layout\_grid.scss */
  .primary {
    float: left;
    direction: ltr;
    padding-left: 12px;
    padding-right: 12px;
  }
}
@media screen and (min-width: 481px) and (max-width: 99999999px) {
  /* line 29, layout\_grid.scss */
  .primary {
    float: left;
    direction: ltr;
    padding-left: 12px;
    padding-right: 12px;
  }
}
@media screen and (min-width: 768px) and (max-width: 99999999px) {
  /* line 29, layout\_grid.scss */
  .primary {
    float: left;
    direction: ltr;
    padding-left: 12px;
    padding-right: 12px;
  }
}
@media screen and (min-width: 1024px) and (max-width: 99999999px) {
  /* line 29, layout\_grid.scss */
  .primary {
    float: left;
    direction: ltr;
    padding-left: 12px;
    padding-right: 12px;
  }
}
@media screen and (min-width: 1200px) and (max-width: 99999999px) {
  /* line 29, layout\_grid.scss */
  .primary {
    float: left;
    direction: ltr;
    padding-left: 12px;
    padding-right: 12px;
  }
}
@media screen and (max-width: 99999999px) {
  /* line 29, layout\_grid.scss */
  .primary {
    width: 100%;
  }
}
```

My states:

```SCSS
@include gridle_register_state( palm, (
    max-width : 480px
) );

@include gridle_register_state( lap-and-up, (
    min-width : 481px
) );

@include gridle_register_state( tab, (
    min-width : 768px
) );

@include gridle_register_state( desk, (
    min-width : 1024px
) );

@include gridle_register_state( desk-wide, (
    min-width : 1200px
) );
```

Is there any way to clean it up?

Thanks!
