### ISSUE TITLE
problem using gridle-push inside gridle_state

### ISSUE THREAD

**Issue by heaversm** [olivierbossel/gridle#31]
Hi - I'm trying to adjust the position of a grid element at a certain breakpoint. I've used breakpoint-sass to do this in the past, and am trying to apply the same methodology to gridle, but it gives me an error.

Here's my code:

```
//_settings.scss
@include gridle_register_state( tablet, (
    max-width : 768px,
) );

//_header.scss
h1 {
        font-size: em(24);
        @include gridle ( 14 );
        @include gridle-push(1);
        @include centerVertical();

        @include gridle_state ( tablet ) {
            @include gridle-push(0);
        }

    }
```

And here's the error:

```
"Sass::SyntaxError: You may not @extend an outer selector from within @media.\A You may only @extend selectors within the same directive.\A From \"@extend %gridle-push-pull-common\" on line 65 of /sass/gridle/_common-mixins.scss.\A "

```

**Comment by olivierbossel** [comment]
Hi man,

Thanks for the interest you have in gridle.
Your issue isn't a real one cause it's a sass limitation. It's impossible to use mixins inside a @media query, which is used in the gridle_state mixin.
To do what you want you can do either :

```scss
@include gridle_push(0, tablet);
```

or if you have more that one property to change for a particular state, you can do :

```scss
@include gridle_set( (
    push : 0,
    grid : 10,
    prefix : 4
), tablet);
```

Your code can be so :

```scss
h1 {
        font-size: em(24);
        @include centerVertical();

        // using gridle_set
        @include gridle_set( (
                grid : 14,
                push : 1,
                tablet : (
                        push : 0
                )
        ) );
}
```

Do not forget to check the documentation about gridle_set mixin.

Let me know if that's ok for you like this :)

Cheers!
