### ISSUE TITLE
Getting State Properties

### ISSUE THREAD

**Issue by veganista** [olivierbossel/gridle#44]
What's the recommended way of getting state variables.

I see this function `_gridle_get_state_var` but it looks like this isn't part of the public API to me due to the underscore prefix.

Thanks

**Comment by olivierbossel** [comment]
Hi,

It's the right way to do it.
I will make these function public so you will be able to use them without the _
I was not thinking that someone will need access to this :)

What is your use for that?

Cheers!

**Comment by veganista** [comment]
To be honest, i've not used them much in my previous projects but did a few times in my last project.

I've used it in 2 places ( both could have been done in other ways )

The first place i used it was to set the maximum width of something to the `min-width` of a breakpoint as i never wanted that container to grow larger.
```scss
    @include gridle_state ( 'small' ) {
        //...
        .section-home-content,
        .section-home-aside {
            max-width: _gridle_get_state_var('medium', 'min-width');
            margin: 0 auto;
        }
    }
```
And secondly i used it to create a very specific state that i was only going to use once. When creating my main states i only use `min-width` and never a `max-width` however in this instance i needed to target my `small` state only and nothing larger. This is probably an edge case though and i could have done this by creating more breakpoints.

```scss
    // this targets small screens only and prevents us repeating ourselves
    // could create *-only states
    @include gridle_state ( (
        'min-width': _gridle_get_state_var('small', 'min-width'),
        'max-width': _gridle_get_state_var('medium', 'min-width')-1
    ) ) {
        //...
        }
    }
```

As i said i could have achieved these in different ways but they were very specific instances and i didn't want the overhead of creating classes for states i was only using once.
