### ISSUE TITLE
Invalid column sizes

### ISSUE THREAD

**Issue by GR3S** [olivierbossel/gridle#74]
In output total width of columns greater than the width of the container. (i think gutter sizes ingored in calculations, or box-sizing isn't set). Version 2.0.

Input:
```scss
@import '../bower_components/gridle/sass/gridle/gridle';

$gridle-container-name-pattern: ('grid');
$gridle-grid-name-pattern: ('grid__module','%-','%state','%-','%count');

@include gridle_setup((
	gutter-width: 40px,
	classes-prefix: 'b-'
));

@include gridle_set_classname_map(container, ('grid', '@', '%state'));
@include gridle_set_classname_map(row, ('grid__row', '_', '%reverse', '@', '%state'));
@include gridle_set_classname_map(grid, ('grid__module', '-', '%column', '@', '%state'));
@include gridle_set_classname_map(row-debug, ('grid__row', '_', 'debug', '@', '%state'));

@include gridle_generate_classes(default, container row grid debug);
```

Output:
```css
.b-grid:after {
  content: "";
  display: table;
  clear: both; }

.b-grid__row:before,
.b-grid__row_reverse:before,
.b-grid__row:after, .b-grid__row_reverse:after {
  content: "";
  display: table; }

.b-grid__row:after, .b-grid__row_reverse:after {
  clear: both; }

.b-grid__row, .b-grid__row_reverse {
  zoom: 1; }

.b-grid__module-0, .b-grid__module-1, .b-grid__module-2, .b-grid__module-3, .b-grid__module-4, .b-grid__module-5, .b-grid__module-6, .b-grid__module-7, .b-grid__module-8, .b-grid__module-9, .b-grid__module-10, .b-grid__module-11, .b-grid__module-12 {
  display: inline-block;
  min-height: 1px;
  float: left;
  padding-right: 20px;
  padding-left: 20px; }

@media screen and (max-width: 400px) {
  @-ms-viewport {
    width: device-width; } }

#gridle-settings {
  content: '{ \\"version\\" : \\"2.0.0\\", \\"states\\" : { \\"default\\":{ \\"name\\" : \\"default\\", \\"min-width\\" : null, \\"max-width\\" : null, \\"query\\" : null, \\"classes\\" : true, \\"context\\" : \\"12\\", \\"gutter-width\\" : \\"40px\\", \\"gutter-height\\" : \\"0\\", \\"gutter-top\\" : \\"0\\", \\"gutter-right\\" : \\"20px\\", \\"gutter-bottom\\" : \\"0\\", \\"gutter-left\\" : \\"20px\\", \\"direction\\" : \\"ltr\\", \\"name-multiplicator\\" : \\"1\\", \\"states-classes\\" : false, \\"classes-prefix\\" : \\"b-\\", \\"_\\" : true }} }'; }

.b-grid__module-0 {
  width: 0%; }

.b-grid__module-1 {
  width: 8.33333%; }

.b-grid__module-2 {
  width: 16.66667%; }

.b-grid__module-3 {
  width: 25%; }

.b-grid__module-4 {
  width: 33.33333%; }

.b-grid__module-5 {
  width: 41.66667%; }

.b-grid__module-6 {
  width: 50%; }

.b-grid__module-7 {
  width: 58.33333%; }

.b-grid__module-8 {
  width: 66.66667%; }

.b-grid__module-9 {
  width: 75%; }

.b-grid__module-10 {
  width: 83.33333%; }

.b-grid__module-11 {
  width: 91.66667%; }

.b-grid__module-12 {
  width: 100%;
  display: inline-block; }

.b-grid__row {
  padding-left: 0 !important;
  padding-right: 0 !important; }

.b-grid__row_reverse {
  padding-left: 0 !important;
  padding-right: 0 !important; }

.b-grid__row_debug {
  position: relative;
  z-index: 99999;
  overflow: hidden; }
  .b-grid__row_debug:before {
    pointer-events: none;
    content: '';
    position: absolute;
    top: 0;
    left: 0;
    width: 100%;
    height: 99999px;
    background: linear-gradient(to right, transparent 50%, rgba(0, 0, 0, 0.02) 50%);
    background-size: 16.66667% 100%;
    z-index: 99999; }

body {
  direction: ltr; }

[class*="b-grid__module"] > [class*="b-grid__row"],
[class*="b-grid__module"] > [class*="b-col"] {
  margin-left: -20px;
  margin-right: -20px; }
```

With box-sizing: border-box all works fine.

This is missed?
