### ISSUE TITLE
Invalid margin sizes in media queries

### ISSUE THREAD

**Issue by GR3S** [olivierbossel/gridle#84]
Input:
```scss
@import '../bower_components/gridle/sass/gridle/gridle';

$gridle-generate-json-settings: false;

$gutter-size: 40px;

@include gridle_setup((
	gutter-width: $gutter-size,
	gutter-height: $gutter-size,
	classes-prefix: 'b-'
));

@include gridle_set_classname_map(container, ('grid', '@', '%state'));
@include gridle_set_classname_map(row, ('grid__row', '_', '%reverse', '@', '%state'));
@include gridle_set_classname_map(row-align, ('grid__row', '_', 'align', '_', '%align', '@', '%state'));
@include gridle_set_classname_map(nowrap, ('grid__nowrap', '@', '%state'));
@include gridle_set_classname_map(grid, ('grid__module', '-', '%column', '@', '%state'));
@include gridle_set_classname_map(grid-adapt, ('grid__module', '-', 'adapt', '@', '%state'));
@include gridle_set_classname_map(grid-grow, ('grid__module', '-', 'grow', '@', '%state'));
@include gridle_set_classname_map(gutter, ('grid__module_gutter', '_', '%side', '@', '%state'));
@include gridle_set_classname_map(no-gutter, ('grid__module_gutter', '_', 'no', '-', '%side', '@', '%state'));
@include gridle_set_classname_map(prefix, ('grid__module_prefix', '_', '%column', '@', '%state'));

@include gridle_generate_classes(default, container row row-align nowrap grid grid-adapt grid-grow gutter no-gutter prefix);
```

Output contins invalid margin rules:
```css
@media (-webkit-min-device-pixel-ratio: 2), (-o-min-device-pixel-ratio: 2/1), (min-resolution: 192dpi), (min-resolution: 2dppx) {
  [class*="b-grid__module"] > [class*="b-grid__row"],
  [class*="b-grid__module"] > [class*="b-col"] {
    margin-left: -;
    margin-right: -; } }

@media only tv {
  [class*="b-grid__module"] > [class*="b-grid__row"],
  [class*="b-grid__module"] > [class*="b-col"] {
    margin-left: -;
    margin-right: -; } }

@media only print {
  [class*="b-grid__module"] > [class*="b-grid__row"],
  [class*="b-grid__module"] > [class*="b-col"] {
    margin-left: -;
    margin-right: -; } }

@media only screen and (orientation: portrait) {
  [class*="b-grid__module"] > [class*="b-grid__row"],
  [class*="b-grid__module"] > [class*="b-col"] {
    margin-left: -;
    margin-right: -; } }

@media only screen and (orientation: landscape) {
  [class*="b-grid__module"] > [class*="b-grid__row"],
  [class*="b-grid__module"] > [class*="b-col"] {
    margin-left: -;
    margin-right: -; } }
```
