### ISSUE TITLE
Issue with placeholder classes in libsass

### ISSUE THREAD

**Issue by panec** [olivierbossel/gridle#94]
In the example of the grid with mixins add in the file grid_mixins.scss add this:
```sass
.list__item {
	background:#DEDEDE;

	&:nth-child(1) {
		@include gridle(6);
	}
	&:nth-child(2){
		@include gridle(6);
	}
}
```

This generates the code for the items properly, but for the generic styles that are bundled via _grid_common_grid we receive following selector:
```css
.my-grid-12, .my-grid-6, #site_header,
  #site_footer, #site_content, #site_sidebar, .gallery__item, .list__item:nth-child(1) {
```
that lacks the selector for the .list__item:nth-child(2).

I was using `node-sass@3.4.2` that was fetched by default in your package.

I'm attaching zip with the updated code:
[gridle.zip](https://github.com/olivierbossel/gridle/files/78345/gridle.zip)

**Comment by olivierbossel** [comment]
Hi,

I've checked your issue on my machine and it seams to be an compiler issue. When I compile with grunt "compass" it's all ok but with grunt sass or gulp sass I got the same issue as you.

```scss
%coco {
	content : 'coco';
}
.my-list-item {
	content : 'my list item';

	&:nth-child(1) {
		content : 'coco 1';
		@extend %coco;
	}
	&:nth-child(2) {
		content : 'coco 2';
		@extend %coco;
	}
}
```

It seems to be an extend issue in the libsass library https://github.com/sass/libsass/issues/1729

For now there's no workaround known sorry.. You will have to find something by yourself until the issue will be fixed...
