### ISSUE TITLE
Problem with @include gridle( container );

### ISSUE THREAD

**Issue by sikeane** [olivierbossel/gridle#97]
I have a strange problem. This might be a little hard to explain so please bare with me. When using @include gridle( container ); it adds prepends the class to its children when setting grid count but not when setting other elements.

My SCSS

```scss
.hero {
    @include gridle(
        container
    );
}

.hero-wrap {
    @include gridle(
        12 grid-centered
        bk-m 8
    );
}
```

For .hero-wrap For bk-m this outputs
```css
@media screen and (min-width: 770px) {
.hero .hero-wrap {
    display: inline-block;
    min-height: 1px;
    float: left;
    box-sizing: border-box;
    vertical-align: top;
    padding-top: 15px;
    padding-right: 15px;
    padding-bottom: 15px;
    padding-left: 15px;
}
.hero-wrap {
    width: 66.6666666667%;
    padding-top: 0;
    padding-right: 0;
    padding-bottom: 0;
    padding-left: 0;
  }
}
```

This means means the margin for .hero-wrap is not getting applied as '.hero .hero-wrap' is to specific to be overridden. Am I doing something wrong? Is this a bug? I guess a simple solution would be to prevent .hero being added before .her-wrap in the css?

The same happens with setting the gutter like so 'gutter 15px 15px 30px 15px'.
